function mirr_height=mirr_func2(x,y,parameter)
    mirr_height = parameter(1)*x + parameter(2)*y + ...
                  parameter(3)*x*y +...
                  parameter(4)*x^2 + parameter(5)*y^2 +...
                  parameter(6)*x^2*y + parameter(7)*x*y^2 +...
                  parameter(8)*x^2*y^2 +...
                  parameter(9)*x^3 + parameter(10)*y^3 +...
                  parameter(11)*x^3*y + parameter(12)*x*y^3 + ...
                  parameter(13)*x^3*y^2 + parameter(14)*x^2*y^3 +...
                  parameter(15)*x^3*y^3 +...
                  parameter(16)*x^4 + parameter(17)*y^4 +...
                  parameter(18)*x^4*y + parameter(19)*x*y^4 +...
                  parameter(20)*x^4*y^2 + parameter(21)*x^2*y^4 +...
                  parameter(22)*x^4*y^3 + parameter(23)*x^3*y^4 +...
                  parameter(24)*x^4*y^4 +...
                  parameter(25)*x^5 + parameter(26)*y^5 +...
                  parameter(27)*x^5*y + parameter(28)*x*y^5 +...
                  parameter(29)*x^5*y^2 + parameter(30)*x^2*y^5 +...
                  parameter(31)*x^5*y^3 + parameter(32)*x^3*y^5 +...
                  parameter(33)*x^5*y^4 + parameter(34)*x^4*y^5 +...
                  parameter(35)*x^5*y^5 ;
end